//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coinsways.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitCoinsTransactionDetail
    {
        public int ID { get; set; }
        public long UserID { get; set; }
        public string BitCoinAccountNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ReferenceDetails { get; set; }
        public decimal Amount { get; set; }
        public int PaymentModeID { get; set; }
        public int CurrencyID { get; set; }
    
        public virtual CurrencyCode CurrencyCode { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
