//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coinsways.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoinswaysDbEntities : DbContext
    {
        public CoinswaysDbEntities()
            : base("name=CoinswaysDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ComissionType> ComissionTypes { get; set; }
        public virtual DbSet<CurrencyCode> CurrencyCodes { get; set; }
        public virtual DbSet<DailyCommission> DailyCommissions { get; set; }
        public virtual DbSet<HelpDeskQuery> HelpDeskQueries { get; set; }
        public virtual DbSet<HelpType> HelpTypes { get; set; }
        public virtual DbSet<LevelCommission> LevelCommissions { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PlanDetail> PlanDetails { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetails { get; set; }
        public virtual DbSet<TransactionStatu> TransactionStatus { get; set; }
        public virtual DbSet<TypeOfTransaction> TypeOfTransactions { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserParentDetail> UserParentDetails { get; set; }
        public virtual DbSet<BitCoinsTransactionDetail> BitCoinsTransactionDetails { get; set; }
    
        public virtual ObjectResult<sp_get_direct_referal_Result> sp_get_direct_referal(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_direct_referal_Result>("sp_get_direct_referal", userIdParameter);
        }
    
        public virtual ObjectResult<sp_get_user_tree_Result> sp_get_user_tree(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_user_tree_Result>("sp_get_user_tree", userIdParameter);
        }
    }
}
