//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coinsways.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpDeskQuery
    {
        public int Id { get; set; }
        public long UserId { get; set; }
        public int HelpTypeId { get; set; }
        public string Message { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual HelpType HelpType { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
