//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coinsways.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public decimal CreditAmount { get; set; }
        public decimal DebitAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PlanID { get; set; }
        public int PayModeID { get; set; }
        public int TypeOfTransactionID { get; set; }
        public string PaymentReferencialDetails { get; set; }
        public string OtherDetails { get; set; }
        public int TransactionStatusID { get; set; }
        public bool IsActive { get; set; }
        public int CommissionTypeID { get; set; }
    
        public virtual ComissionType ComissionType { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PlanDetail PlanDetail { get; set; }
        public virtual TransactionStatu TransactionStatu { get; set; }
        public virtual TypeOfTransaction TypeOfTransaction { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
