//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coinsways.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.HelpDeskQueries = new HashSet<HelpDeskQuery>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
            this.UserParentDetails = new HashSet<UserParentDetail>();
            this.UserParentDetails1 = new HashSet<UserParentDetail>();
            this.BitCoinsTransactionDetails = new HashSet<BitCoinsTransactionDetail>();
        }
    
        public long UserId { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FatherOrHusband { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public bool IsActive { get; set; }
        public bool IsParentAdded { get; set; }
        public bool IsPlanAdded { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string BitcoinNumber { get; set; }
        public Nullable<bool> IsReferred { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelpDeskQuery> HelpDeskQueries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserParentDetail> UserParentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserParentDetail> UserParentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitCoinsTransactionDetail> BitCoinsTransactionDetails { get; set; }
    }
}
